# ML Introduction - Homework

In [1]:
import numpy as np
from numpy.linalg import inv
import pandas as pd

## Question 1

In [2]:
# What's the version of Pandas that you installed?

pd.__version__

'1.4.4'

## Getting the data

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-16 15:53:43--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: 'housing.csv.2'

     0K .......... .......... .......... .......... ..........  3%  639K 2s
    50K .......... .......... .......... .......... ..........  7%  506K 2s
   100K .......... .......... .......... .......... .......... 10%  633K 2s
   150K .......... .......... .......... .......... .......... 14%  597K 2s
   200K .......... .......... .......... .......... .......... 17%  724K 2s
   250K .......... .......... .......... .......... .......... 21%  666K 2s
   300K .......... .......... .......... .......... .......... 25%  675K 2s
   350K .......... .......... 

In [4]:
df = pd.read_csv('housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

## Question 2

In [5]:
# How many columns are in the dataset?

columns_number = len([*df.columns])
print(f'Dataset contains {columns_number} columns.')

Dataset contains 10 columns.


## Question 3

In [6]:
# Which columns in the dataset have missing values?

df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## Question 4

In [7]:
# How many unique values does the ocean_proximity column have?

df.ocean_proximity.nunique()

5

## Question 5

In [8]:
# What's the average value of the median_house_value for the houses located near the bay?

df[df.ocean_proximity == 'NEAR BAY'].median_house_value.mean()

259212.31179039303

## Question 6

In [9]:
# Calculate the average of total_bedrooms column in the dataset.

total_bedrooms_average_before = df.total_bedrooms.mean()
total_bedrooms_average_before

537.8705525375618

In [10]:
# Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.

df.total_bedrooms = df.total_bedrooms.fillna(total_bedrooms_average_before)

# Check if all columns do not have missing values.

sum(df.isnull().sum().values) == 0

True

In [11]:
# Calculate the average of total_bedrooms again.

total_bedrooms_average_after = df.total_bedrooms.mean()
total_bedrooms_average_after

537.8705525375639

In [12]:
diff = round(total_bedrooms_average_before, 3) - round(total_bedrooms_average_after, 3)

if diff == 0:
    print('The avarage of total_bedrooms has not changed.')
else:
    print(f'The avarage of total_bedrooms has not changed. The difference is {diff}.')

The avarage of total_bedrooms has not changed.


## Question 7

In [13]:
# Select all the options located on islands.

df = df[df.ocean_proximity == 'ISLAND']
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [14]:
# Select only columns housing_median_age, total_rooms, total_bedrooms.

df = df[['housing_median_age', 'total_rooms', 'total_bedrooms']]
df

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [15]:
# Get the underlying NumPy array. Let's call it X.

X = df.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [16]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

XTX = X.T @ X
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [17]:
# Compute the inverse of XTX.

XTX_inverse = inv(XTX)
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [18]:
# Create an array y with values [950, 1300, 800, 1000, 1300].

y = [950, 1300, 800, 1000, 1300]

In [19]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = (XTX_inverse @ X.T).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [20]:
print(f'The value of the last element of w is {w[-1]}')

The value of the last element of w is 5.699229455065578
